apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    zarf.dev/agent: ignore
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test
spec:
  containers:
    - name: test-container
      image: ghcr.io/stefanprodan/podinfo:6.7.1@sha256:862ca45e61b32392f7941a1bdfdbe5ff8b6899070135f1bdca1c287d0057fc94
      command:
        - ./podinfo
