variables:
  - name: AWS_DIR
    default: "packer/aws"
    description: "Directory containing AWS packer config"
  - name: UBUNTU_PRO_TOKEN
    default: ""
    description: "Optional: provide Ubuntu pro token if using Ubuntu + FIPS"
  - name: AWS_REGION
    default: "us-west-2"
    description: "AWS region to build the AMI in"
  - name: PUBLISH_REGIONS
    default: "[]"
    description: "List of regions to copy the final AMI to when publishing, with escaped quotes, ex: '[\"us-west-1\"]'"
  - name: PUBLISH_GROUPS
    default: "[]"
    description: "List of groups to allow access to the AMI. Only supports '[]' or '[\"all\"]'"
  - name: AWS_ORG_ARNS
    default: "[]"
    description: "A list of Amazon Resource Names (ARN) of AWS Organizations that have access to launch the resulting AMI(s). By default no organizations have permission to launch the AMI."
  - name: AMI_USERS
    default: "[]"
    description: "A list of account IDs that have access to launch the resulting AMI(s). By default no additional users other than the user creating the AMI has permissions to launch it."
  - name: RKE2_VERSION
    default: "v1.29.10+rke2r1"
    description: "RKE2 version to build the AMI with"

tasks:
  - name: publish-ami-ubuntu
    description: "Build and Publish the Ubuntu AMI for AWS"
    actions:
      - cmd: |
          cd ${AWS_DIR}
          packer init .
          packer build -var "ubuntu_pro_token=${UBUNTU_PRO_TOKEN}" --var-file=ubuntu.pkrvars.hcl -var "region=${AWS_REGION}" -var "ami_regions=${PUBLISH_REGIONS}" -var "ami_groups=${PUBLISH_GROUPS}" -var "aws_org_arns=${AWS_ORG_ARNS} -var "ami_users=${AMI_USERS} -var "rke2_version=${RKE2_VERSION}" .

  - name: publish-ami-rhel
    description: "Build and Publish the RHEL AMI for AWS"
    actions:
      - cmd: |
          cd ${AWS_DIR}
          packer init .
          packer build --var-file=rhel.pkrvars.hcl -var "region=${AWS_REGION}" -var "ami_regions=${PUBLISH_REGIONS}" -var "ami_groups=${PUBLISH_GROUPS}" -var "aws_org_arns=${AWS_ORG_ARNS} -var "ami_users=${AMI_USERS} -var "rke2_version=${RKE2_VERSION}" .

  - name: build-ami-ubuntu
    description: "Build the Ubuntu AMI for AWS"
    actions:
      - cmd: |
          cd ${AWS_DIR}
          packer init .
          packer build -var "skip_create_ami=true" -var "ubuntu_pro_token=${UBUNTU_PRO_TOKEN}" --var-file=ubuntu.pkrvars.hcl -var "region=${AWS_REGION}" -var "rke2_version=${RKE2_VERSION}" .

  - name: build-ami-rhel
    description: "Build the RHEL AMI for AWS"
    actions:
      - cmd: |
          cd ${AWS_DIR}
          packer init .
          packer build -var "skip_create_ami=true" --var-file=rhel.pkrvars.hcl -var "region=${AWS_REGION}" -var "rke2_version=${RKE2_VERSION}" .

  - name: fmt-ami
    description: "Run packer fmt for the AWS AMIs"
    actions:
      - cmd: cd ${AWS_DIR} && packer fmt .

  - name: validate-ami-ubuntu
    description: "Run packer validation for the AWS Ubuntu AMI"
    actions:
      - cmd: |
          cd ${AWS_DIR}
          packer init .
          packer validate --var-file=ubuntu.pkrvars.hcl -var "region=${AWS_REGION}" -var "rke2_version=${RKE2_VERSION}" .

  - name: validate-ami-rhel
    description: "Run packer validation for the AWS RHEL AMI"
    actions:
      - cmd: |
          cd ${AWS_DIR}
          packer init .
          packer validate --var-file=rhel.pkrvars.hcl -var "region=${AWS_REGION}" -var "rke2_version=${RKE2_VERSION}" .
