name: AWS AMI

on:
  pull_request:
    branches:
      - main
    paths:
      - "packer/aws/**"
      - "packer/scripts/**"
      - ".github/workflows/on-pr-aws.yaml"

permissions:
  id-token: write
  contents: read
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          # 21600 seconds == 6 hours
          role-duration-seconds: 21600
      - name: Validate AMI
        run: make validate-ami
      - name: Build AMI
        run: make build-ami
