name: AWS AMI

on:
  pull_request:
    branches:
      - main
    paths:
      - "packer/aws/**"
      - "packer/scripts/**"
      - ".github/workflows/on-pr-aws.yaml"
      - "tasks/aws.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["ubuntu", "rhel"]
        aws_env: ["commercial", "govcloud"]
        rke2_version: ["v1.32.6+rke2r1]
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set AWS Variables
        run: |
          if [ "${{ matrix.aws_env }}" == "commercial" ]; then
            echo "AWS_REGION=us-west-2" >> $GITHUB_ENV
            echo "AWS_ORG_ROLE_TO_ASSUME=${{ secrets.AWS_COMMERCIAL_ORG_ROLE_TO_ASSUME }}" >> $GITHUB_ENV
          elif [ "${{ matrix.aws_env }}" == "govcloud" ]; then
            echo "AWS_REGION=us-gov-west-1" >> $GITHUB_ENV
            echo "AWS_ORG_ROLE_TO_ASSUME=${{ secrets.AWS_GOVCLOUD_ORG_ROLE_TO_ASSUME }}" >> $GITHUB_ENV
          fi
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ env.AWS_ORG_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
      - name: Install UDS CLI
        uses: defenseunicorns/setup-uds@ab842abcad1f7a3305c2538e3dd1950d0daacfa5 # v1.0.1
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.27.7
      - name: Validate ${{ matrix.base }} ${{ matrix.aws_env }} AMI
        run: uds run --no-progress validate-ami-${{ matrix.base }} --set AWS_REGION=${{ env.AWS_REGION }} --set RKE2_VERSION=${{ matrix.rke2_version }}
      - name: Build ${{ matrix.base }} ${{ matrix.aws_env }} AMI
        run: uds run --no-progress build-ami-${{ matrix.base }} --set AWS_REGION=${{ env.AWS_REGION }} --set RKE2_VERSION=${{ matrix.rke2_version }}
