name: AWS AMI

on:
  push:
    branches:
      - main
    paths:
      - "packer/aws/**"
      - "packer/scripts/**"
      - ".github/workflows/publish-aws.yaml"
  schedule:
    - cron: '0 6 1 * *' # Runs monthly at midnight MST

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: ["ubuntu", "rhel"]
        aws_env: ["commercial", "govcloud"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Set AWS Variables
        run: |
          if [ "${{ matrix.aws_env }}" == "commercial" ]; then
            echo "AWS_REGION=us-west-2" >> $GITHUB_ENV
            echo "AWS_ORG_ROLE_TO_ASSUME=${{ secrets.AWS_COMMERCIAL_ORG_ROLE_TO_ASSUME }}" >> $GITHUB_ENV
          elif [ "${{ matrix.aws_env }}" == "govcloud" ]; then
            echo "AWS_REGION=us-gov-west-1" >> $GITHUB_ENV
            echo "AWS_ORG_ROLE_TO_ASSUME=${{ secrets.AWS_GOVCLOUD_ORG_ROLE_TO_ASSUME }}" >> $GITHUB_ENV
          fi
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ env.AWS_ORG_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: ${{ env.AWS_REGION }}
          # 21600 seconds == 6 hours
          role-duration-seconds: 21600
      - name: Setup UDS
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/setup@a6fba9c0084319325d70816a3481aec0979649fa # v0.4.0
      - name: Setup Tofu
        uses: opentofu/setup-opentofu@ae80d4ecaab946d8f5ff18397fbf6d0686c6d46a # v1.0.3
        with:
          tofu_wrapper: false
          tofu_version: 1.6.2
      - name: Publish ${{ matrix.base }} AMI
        run: uds run --no-progress publish-ami-${{ matrix.base }} --set AWS_REGION=${{ env.AWS_REGION }}
      - name: Test ${{ matrix.base }} AMI
        shell: bash -e -o pipefail {0}
        env:
          KUBECONFIG: "/home/runner/.kube/rke2-config"
        run: uds run --no-progress test-cluster --set SHA=${{ github.sha }} --set DISTRO=${{ matrix.base }} --set AWS_REGION=${{ env.AWS_REGION }}
      - name: Teardown test infrastructure
        shell: bash -e -o pipefail {0}
        if: always()
        run: uds run --no-progress teardown-infra --set DISTRO=${{ matrix.base }} --set AWS_REGION=${{ env.AWS_REGION }}
      - name: Cleanup ${{ matrix.base }} AMI on failure
        shell: bash -e -o pipefail {0}
        if: failure()
        run: uds run --no-progress cleanup-ami --set AWS_REGION=${{ env.AWS_REGION }}
