name: AWS AMI

on:
  push:
    branches:
      - main
    paths:
      - "packer/aws/**"
      - "packer/scripts/**"
      - ".github/workflows/publish-aws.yaml"
  schedule:
    - cron: '0 6 1 * *' # Runs monthly at midnight MST

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: ["ubuntu", "rhel"]
        # TODO: Can we add a renovate config for these?
        rke2_version: ["v1.28.11+rke2r1", "v1.29.6+rke2r1", "v1.30.2+rke2r1"]
        aws_env: ["commercial"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ORG_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          # 21600 seconds == 6 hours
          role-duration-seconds: 21600
      - name: Setup UDS
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/setup@a6fba9c0084319325d70816a3481aec0979649fa # v0.4.0
      - name: Setup Tofu
        uses: opentofu/setup-opentofu@ae80d4ecaab946d8f5ff18397fbf6d0686c6d46a # v1.0.3
        with:
          tofu_wrapper: false
          tofu_version: 1.6.2
      - name: Publish ${{ matrix.base }} ${{rke2_version}} AMI
        run: uds run --no-progress publish-ami-${{ matrix.base }} --set RKE2_VERSION=${{ matrix.rke2_version }}
      - name: Test ${{ matrix.base }} ${{rke2_version}} AMI
        shell: bash -e -o pipefail {0}
        env:
          KUBECONFIG: "/home/runner/.kube/rke2-config"
        run: uds run --no-progress test-cluster --set SHA=${{ github.sha }} --set DISTRO=${{ matrix.base }}
      - name: Teardown test infrastructure
        shell: bash -e -o pipefail {0}
        if: always()
        run: uds run --no-progress teardown-infra --set DISTRO=${{ matrix.base }}
      - name: Cleanup ${{ matrix.base }} ${{rke2_version}} AMI on failure
        shell: bash -e -o pipefail {0}
        if: failure()
        run: uds run --no-progress cleanup-ami
