# When someone with write access to the repo adds a comment to a PR that contains "/update <command>", dispatch the workflow found in "update-command.yml"

name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
permissions:
  id-token: write
  contents: write # For executing the repository_dispatch event
  pull-requests: write # For doing the emoji reaction on a PR comment
jobs:
  slashCommandDispatchTest:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: test
          permission: write
          issue-type: pull-request
